### PR TITLE
Attempt to use parallelization to make test faster

### PR DESCRIPTION
**Pull request by hdoupe**
I tried to take advantage of the pytest fixtures and parametrization functionality to make this test faster.  It runs in about 215 seconds now.  I hoped that doing this would result in a greater speed up.  Maybe someone else will see something that I'm missing.

@MattHJensen @martinholmer

### CODE REVIEW

**Comment by martinholmer** [comment]
@hdoupe said:
> I tried to take advantage of the pytest fixtures and parametrization functionality to make this test faster. It runs in about 215 seconds now. 

How long does it take to execute without your changes?  How much of a speed-up did your changes generate?

**Comment by hdoupe** [comment]
@martinholmer according to you and @MattHJensen it took about [4.6 minutes to run](https://github.com/open-source-economics/Tax-Calculator/pull/1614#issuecomment-346500475) before I made the changes.  After I made the changes, it took about 3.6 minutes to run. So, this is about a minute faster.

**Comment by martinholmer** [comment]
@hdoupe said:
> @martinholmer according to you and @MattHJensen it took about 4.6 minutes to run before I made the changes. After I made the changes, it took about 3.6 minutes to run. So, this is about a minute faster.

Can't compare run times on different computers because there's quite a difference in hardware among Tax-Calculator developers.  What we need is the before-the-changes run time and the after-the-changes run time, both on **your** computer.

**Comment by hdoupe** [comment]
Ah, good point.  Here's the run-time on my computer:

```
(taxcalc-dev) HDoupe-MacBook-Pro:Tax-Calculator henrydoupe$ git branch -D compatible_data
Deleted branch compatible_data (was ec73c47f).
(taxcalc-dev) HDoupe-MacBook-Pro:Tax-Calculator henrydoupe$ git fetch upstream pull/1614/head:compatible_data
From https://github.com/open-source-economics/Tax-Calculator
 * [new ref]           refs/pull/1614/head -> compatible_data
(taxcalc-dev) HDoupe-MacBook-Pro:Tax-Calculator henrydoupe$ git checkout compatible_data
Switched to branch 'compatible_data'
(taxcalc-dev) HDoupe-MacBook-Pro:Tax-Calculator henrydoupe$ git branch
* compatible_data
  compatible_data2
  compatible_data_hank
  master
  remove_agi
  v0.13.2_no_agi
(taxcalc-dev) HDoupe-MacBook-Pro:Tax-Calculator henrydoupe$ py.test -m "pre_release" -n4
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 3.5.4, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /Users/henrydoupe/Documents/Tax-Calculator, inifile: setup.cfg
plugins: xdist-1.17.1, pep8-1.0.6
gw0 [2] / gw1 [2] / gw2 [2] / gw3 [2]
scheduling tests via LoadScheduling
..
========================================================================================================================= 2 passed in 392.18 seconds =========================================================================================================================
```

This resulted in a run-time of 392.18 seconds or 6.5 minutes.  It seemed to take a long time just to schedule the tests.  @martinholmer would you mind running my branch on your computer?

**Comment by martinholmer** [comment]
@hdoupe asked:
> @martinholmer would you mind running my branch on your computer?

Won't be able to do that under Friday at the earliest.  I'm in the midst of moving back from a month in Canada.

**Comment by hdoupe** [comment]
@martinholmer Ok no problem. I'll figure out a way to run this in a more isolated environment where I don't have a hundred open tabs, windows, etc.

**Comment by hdoupe** [comment]
@martinholmer Ok, so I ran the two tests on an AWS machine and my branch finished in 2 minutes (124 secs) while the original branch finished in 4 minutes (234 secs).

**Comment by martinholmer** [comment]
@hdoupe,  that’s impressive: almost twice as fast.  Good work!

**Comment by MattHJensen** [comment]
Thanks very much @hdoupe (and @martinholmer for timing review) Merging.

**Pull request merged**
